# Generated by Django 3.1.1 on 2020-10-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpuspecs', '0002_gpu_board_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='ROM_name',
            field=models.CharField(default='4730_0000_pc0.rom', max_length=100),
            preserve_default=False,
        ),
    ]
