# Generated by Django 3.1.1 on 2020-10-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpuspecs', '0004_login_credentials_test_system'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login_Credentials',
        ),
        migrations.AddField(
            model_name='test_system',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_system',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
