# Generated by Django 3.1.1 on 2020-10-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpuspecs', '0005_auto_20201005_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_system',
            name='Operating_System',
            field=models.CharField(choices=[('Debian', 'Debian'), ('Windows', 'Windows'), ('Ubuntu', 'Ubuntu')], max_length=100),
        ),
    ]
